/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.bean.Clientes;
import model.bean.Produto;
import model.dao.ClienteDAO;
import model.dao.ProdutoDAO;

/**
 *
 * @author biond
 */
public class VisualizarProdutos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VisualizarProdutos.class.getName());

    /**
     * Creates new form Cliente
     */
    public VisualizarProdutos() {
        initComponents();
        MostrarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtConcultaNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtConsultaValor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtConsultaQuantidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtConsultaFabricante = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtConsultaDescricao = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        bntSair5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bntRelatorio6 = new javax.swing.JButton();

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Email", "Genero", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(tableClientes);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("VISUALIZAÇÃO DE PRODUTOS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nome");

        txtConcultaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConcultaNomeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Valor");

        txtConsultaValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaValorActionPerformed(evt);
            }
        });
        txtConsultaValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConsultaValorKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Quantidade");

        txtConsultaQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaQuantidadeActionPerformed(evt);
            }
        });
        txtConsultaQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConsultaQuantidadeKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Fabricante");

        txtConsultaFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaFabricanteActionPerformed(evt);
            }
        });
        txtConsultaFabricante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConsultaFabricanteKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Descrição");

        txtConsultaDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaDescricaoActionPerformed(evt);
            }
        });
        txtConsultaDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConsultaDescricaoKeyPressed(evt);
            }
        });

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Valor", "Quantidade", "Fabricante", "Descricao"
            }
        ));
        tableProdutos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableProdutosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tableProdutos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsultaDescricao)
                            .addComponent(txtConsultaFabricante)
                            .addComponent(txtConsultaQuantidade)
                            .addComponent(txtConsultaValor)
                            .addComponent(txtConcultaNome)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtConcultaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtConsultaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtConsultaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtConsultaFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtConsultaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(90, 90, 90))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        bntSair5.setText("Sair");
        bntSair5.setBorder(null);
        bntSair5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSair5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("SOFTWARES");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("BIONDO");

        bntRelatorio6.setText("Relatório De Produtos");
        bntRelatorio6.setBorder(null);
        bntRelatorio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRelatorio6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bntSair5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(bntRelatorio6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntSair5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(192, 192, 192)
                    .addComponent(bntRelatorio6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(321, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void MostrarTabela()
    {
        
        //ClienteDAO clientedao = new ClienteDAO();
        ProdutoDAO ProdutoDAO = new ProdutoDAO();
        ArrayList<Produto> produtos = ProdutoDAO.listarProduto();
        
        DefaultTableModel modelo = (DefaultTableModel) tableProdutos.getModel();
        modelo.setRowCount(0); // limpa tabela

        // Adiciona cada cliente na tabela
        for (Produto p : ProdutoDAO.listarProduto()) 
        {
            modelo.addRow(new Object[]
            {
                p.getNome(),
                p.getValor(),
                p.getQuantidade(),
                p.getFabricante(),
                p.getDescricao()
            });
        }
    }
    
    private void bntSair5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSair5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bntSair5ActionPerformed

    private void bntRelatorio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRelatorio6ActionPerformed
        new Relatorios.GerarRelatorioProduto().gerar();
    }//GEN-LAST:event_bntRelatorio6ActionPerformed

    private void txtConcultaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConcultaNomeActionPerformed
        
        String nome = "%"+txtConcultaNome.getText()+"%";
        
        ProdutoDAO dao = new ProdutoDAO();
        ArrayList<Produto> lista = dao.listarProdutoNome(nome);
        
        DefaultTableModel dados = (DefaultTableModel) tableProdutos.getModel();
        
        dados.setNumRows(0);
        
        for (Produto p : lista) 
        {
            dados.addRow(new Object[]
            {
                p.getNome(),
                p.getValor(),
                p.getQuantidade(),
                p.getFabricante(),
                p.getDescricao()
            });
        }
    }//GEN-LAST:event_txtConcultaNomeActionPerformed

    private void txtConsultaValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaValorActionPerformed

    private void txtConsultaQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaQuantidadeActionPerformed
        String nome = "%"+txtConsultaQuantidade.getText()+"%";
        
        ProdutoDAO dao = new ProdutoDAO();
        ArrayList<Produto> lista = dao.listarProdutoQuantidade(nome);
        
        DefaultTableModel dados = (DefaultTableModel) tableProdutos.getModel();
        
        dados.setNumRows(0);
        
        for (Produto p : lista) 
        {
            dados.addRow(new Object[]
            {
                p.getNome(),
                p.getValor(),
                p.getQuantidade(),
                p.getFabricante(),
                p.getDescricao()
            });
        }
    }//GEN-LAST:event_txtConsultaQuantidadeActionPerformed

    private void txtConsultaFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaFabricanteActionPerformed

    private void txtConsultaDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaDescricaoActionPerformed

    private void tableProdutosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableProdutosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tableProdutosAncestorAdded

    private void txtConsultaValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaValorKeyPressed
        String nome = "%"+txtConsultaValor.getText()+"%";
        
        ProdutoDAO dao = new ProdutoDAO();
        ArrayList<Produto> lista = dao.listarProdutoValor(nome);
        
        DefaultTableModel dados = (DefaultTableModel) tableProdutos.getModel();
        
        dados.setNumRows(0);
        
        for (Produto p : lista) 
        {
            dados.addRow(new Object[]
            {
                p.getNome(),
                p.getValor(),
                p.getQuantidade(),
                p.getFabricante(),
                p.getDescricao()
            });
        }
    }//GEN-LAST:event_txtConsultaValorKeyPressed

    private void txtConsultaQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaQuantidadeKeyPressed
        String nome = "%"+txtConsultaQuantidade.getText()+"%";
        
        ProdutoDAO dao = new ProdutoDAO();
        ArrayList<Produto> lista = dao.listarProdutoQuantidade(nome);
        
        DefaultTableModel dados = (DefaultTableModel) tableProdutos.getModel();
        
        dados.setNumRows(0);
        
        for (Produto p : lista) 
        {
            dados.addRow(new Object[]
            {
                p.getNome(),
                p.getValor(),
                p.getQuantidade(),
                p.getFabricante(),
                p.getDescricao()
            });
        }
    }//GEN-LAST:event_txtConsultaQuantidadeKeyPressed

    private void txtConsultaFabricanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaFabricanteKeyPressed
        String nome = "%"+txtConsultaFabricante.getText()+"%";
        
        ProdutoDAO dao = new ProdutoDAO();
        ArrayList<Produto> lista = dao.listarProdutoFabricante(nome);
        
        DefaultTableModel dados = (DefaultTableModel) tableProdutos.getModel();
        
        dados.setNumRows(0);
        
        for (Produto p : lista) 
        {
            dados.addRow(new Object[]
            {
                p.getNome(),
                p.getValor(),
                p.getQuantidade(),
                p.getFabricante(),
                p.getDescricao()
            });
        }
    }//GEN-LAST:event_txtConsultaFabricanteKeyPressed

    private void txtConsultaDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaDescricaoKeyPressed
        String nome = "%"+txtConsultaDescricao.getText()+"%";
        
        ProdutoDAO dao = new ProdutoDAO();
        ArrayList<Produto> lista = dao.listarProdutoDescricao(nome);
        
        DefaultTableModel dados = (DefaultTableModel) tableProdutos.getModel();
        
        dados.setNumRows(0);
        
        for (Produto p : lista) 
        {
            dados.addRow(new Object[]
            {
                p.getNome(),
                p.getValor(),
                p.getQuantidade(),
                p.getFabricante(),
                p.getDescricao()
            });
        }
    }//GEN-LAST:event_txtConsultaDescricaoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VisualizarProdutos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntRelatorio6;
    private javax.swing.JButton bntSair5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JTextField txtConcultaNome;
    private javax.swing.JTextField txtConsultaDescricao;
    private javax.swing.JTextField txtConsultaFabricante;
    private javax.swing.JTextField txtConsultaQuantidade;
    private javax.swing.JTextField txtConsultaValor;
    // End of variables declaration//GEN-END:variables
}
